import { MigrationInterface, QueryRunner } from "typeorm";

export class MasterDb1778826656225 implements MigrationInterface {
    name = 'MasterDb1778826656225'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenant_db_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "host" character varying NOT NULL, "port" integer NOT NULL, "database" character varying NOT NULL, "username" character varying NOT NULL, "password" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "tenantId" uuid, CONSTRAINT "REL_59638e8ce71cd06be80bd37c43" UNIQUE ("tenantId"), CONSTRAINT "PK_40e7bedb00643ccc59b1c8828be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "displayName" character varying NOT NULL, "logoUrl" character varying, "phone" character varying, "address" character varying, "supportEmail" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tenant_id" uuid, CONSTRAINT "REL_7755f200fd5c61591cecffa98d" UNIQUE ("tenant_id"), CONSTRAINT "PK_2a7607ec8fe2028dc77670f64c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "modules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a57f2b3bd9ebb022212e634f601" UNIQUE ("key"), CONSTRAINT "PK_7dbefd488bd96c5bf31f0ce0c95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_modules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "enabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tenantId" uuid, "moduleId" uuid, CONSTRAINT "UQ_7f3f26bc515f78df09868642259" UNIQUE ("tenantId", "moduleId"), CONSTRAINT "PK_b0d534b6c523b8b1d5e64aa23c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_industrytype_enum" AS ENUM('SOFTWARE', 'RETAIL', 'SERVICES', 'BRAND', 'MANUFACTURING', 'WHOLESALE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_status_enum" AS ENUM('REGISTERED', 'PROVISIONING', 'PROVISIONED', 'FAILED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "industryType" "public"."tenants_industrytype_enum", "isActive" boolean NOT NULL DEFAULT true, "status" "public"."tenants_status_enum" NOT NULL DEFAULT 'REGISTERED', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3021c18db2b363ae9324c826c5a" UNIQUE ("code"), CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"), CONSTRAINT "UQ_155c343439adc83ada6ee3f48be" UNIQUE ("email"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_provisioning_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying NOT NULL, "startedAt" TIMESTAMP NOT NULL DEFAULT now(), "finishedAt" TIMESTAMP, "errorMessage" text, "tenant_id" uuid, CONSTRAINT "PK_94a5652117329e68e0acd9563aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_provisioning_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" character varying NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "job_id" uuid, CONSTRAINT "PK_fc3e0e87f21e4a99083ab6f28fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_geo_policies_scope_type_enum" AS ENUM('GLOBAL', 'COUNTRY', 'STATE')`);
        await queryRunner.query(`CREATE TABLE "tenant_geo_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_type" "public"."tenant_geo_policies_scope_type_enum" NOT NULL DEFAULT 'GLOBAL', "country_id" character varying, "state_id" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "tenantId" uuid, CONSTRAINT "REL_602f1bfc60fb24dedaa6fbe09a" UNIQUE ("tenantId"), CONSTRAINT "PK_830c809b0b3b6fee5cd4f4aae75" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_settings_currency_enum" AS ENUM('USD', 'SAR', 'KWD', 'AED', 'PKR')`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_settings_baseuom_enum" AS ENUM('PCS', 'LTR', 'KGS')`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_settings_baselocale_enum" AS ENUM('en', 'ar')`);
        await queryRunner.query(`CREATE TABLE "tenant_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timezone" character varying NOT NULL DEFAULT 'UTC', "currency" "public"."tenant_settings_currency_enum" NOT NULL DEFAULT 'USD', "baseUom" "public"."tenant_settings_baseuom_enum" NOT NULL DEFAULT 'PCS', "baseLocale" "public"."tenant_settings_baselocale_enum" NOT NULL DEFAULT 'en', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tenant_id" uuid, CONSTRAINT "REL_a6abc1c3ed0df635955fc852f1" UNIQUE ("tenant_id"), CONSTRAINT "PK_69225c0ca64bcbbf9af8a217043" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_themes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "primaryColor" character varying NOT NULL DEFAULT '#2563eb', "secondaryColor" character varying NOT NULL DEFAULT '#f3f4f6', "accentColor" character varying NOT NULL DEFAULT '#f59e0b', "darkMode" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tenant_id" uuid, CONSTRAINT "REL_b1c6aaa6ddcc8ff38da4496cec" UNIQUE ("tenant_id"), CONSTRAINT "PK_b1ccffa44c6d16541f76d6702c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "stripe_price_id" character varying, "payfast_price_id" character varying, "slug" character varying NOT NULL, "description" character varying NOT NULL, "currency" character varying NOT NULL, "price" character varying NOT NULL, "billing_cycle" character varying NOT NULL, "is_active" boolean NOT NULL, "is_display" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."plan_limits_limitkey_enum" AS ENUM('USER', 'STORAGE', 'BUSINESS')`);
        await queryRunner.query(`CREATE TABLE "plan_limits" ("id" SERIAL NOT NULL, "limitKey" "public"."plan_limits_limitkey_enum" NOT NULL, "limitValue" integer NOT NULL, "plan_id" integer, CONSTRAINT "PK_7e1766a42b4f6a5d98a04eb4ba9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addons" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "stripe_price_id" character varying, "payfast_price_id" character varying, "slug" character varying NOT NULL, "description" character varying NOT NULL, "price" character varying NOT NULL, "limitKey" character varying NOT NULL, "limitValue" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'PKR', "is_active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cd49fb3dc0558f02cb6fe6cc138" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingmodel_enum" AS ENUM('SELF_SERVE', 'SALES_DRIVEN')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_paymentmode_enum" AS ENUM('ONLINE', 'OFFLINE')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_collectiontype_enum" AS ENUM('AUTO', 'MANUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('ACTIVE', 'PAST_DUE', 'SUSPENDED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" SERIAL NOT NULL, "billingModel" "public"."subscriptions_billingmodel_enum" NOT NULL, "paymentMode" "public"."subscriptions_paymentmode_enum" NOT NULL, "collectionType" "public"."subscriptions_collectiontype_enum" NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "cancelledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tenant_id" uuid, "planId" integer, CONSTRAINT "REL_f6ac03431c311ccb8bbd7d3af1" UNIQUE ("tenant_id"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscription_addons" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "subscription_id" integer, "addon_id" integer, CONSTRAINT "PK_2648ce4c6031da6cfb93f33665e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "title" text NOT NULL, "message" text NOT NULL, "type" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "fullName" character varying NOT NULL, "passwordHash" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "role_id" uuid NOT NULL, CONSTRAINT "UQ_b616fa69a7b331fc2a7906a83d2" UNIQUE ("email"), CONSTRAINT "PK_69bfedb2b67d1014d7b7741f5b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0c27defb5e677a03b7ff0f45ceb" UNIQUE ("code"), CONSTRAINT "PK_598e373288278aa5dc8f1c2731b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_permissions" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_26a58814066e4035d0ca91c162a" UNIQUE ("code"), CONSTRAINT "PK_51c9eb8faa285e4352508f88440" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "countries" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "iso_code" character varying(10) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa1376321185575cf2226b1491" ON "countries" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_31d60a54633e88225b40081e18" ON "countries" ("iso_code") `);
        await queryRunner.query(`CREATE TABLE "states" ("id" SERIAL NOT NULL, "country_id" integer NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_09ab30ca0975c02656483265f4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "fullName" character varying NOT NULL, "passwordHash" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "email_verified_at" TIMESTAMP, "phone" character varying NOT NULL, "country" character varying NOT NULL, "email_verification_otp" character varying, "email_verification_otp_expires_at" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8536b8b85c06969f84f0c098b03" UNIQUE ("email"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'ISSUE', 'PAID', 'OVERDUE')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" SERIAL NOT NULL, "status" "public"."invoices_status_enum" NOT NULL, "issueDate" TIMESTAMP NOT NULL, "dueDate" TIMESTAMP NOT NULL, "subTotalAmount" integer NOT NULL, "taxAmount" integer NOT NULL, "totalAmount" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tenant_id" uuid, "subscription_id" integer, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "quantity" integer NOT NULL, "unitPrice" integer NOT NULL, "totalAmount" integer NOT NULL, "invoice_id" integer, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_payments_method_enum" AS ENUM('CASH', 'CHEQUE', 'TRANSFER', 'ONLINE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "invoice_payments" ("id" SERIAL NOT NULL, "paymentDate" TIMESTAMP NOT NULL, "amount" character varying NOT NULL, "method" "public"."invoice_payments_method_enum" NOT NULL, "remarks" character varying, "reference" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "invoice_id" integer, CONSTRAINT "PK_e19c9ebfa432289f510de7b4e99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cities" ("id" SERIAL NOT NULL, "state_id" integer NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(20), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4762ffb6e5d198cfec5606bc11e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_actortype_enum" AS ENUM('PLATFORM_USER', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorType" "public"."activity_logs_actortype_enum" NOT NULL, "actorId" uuid, "tenantId" uuid, "action" character varying NOT NULL, "description" text, "metadata" jsonb, "jobId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_displaymode_enum" AS ENUM('BANNER', 'MODAL')`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_type_enum" AS ENUM('INFO', 'WARNING', 'ERROR', 'SUCCESS')`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_targetscope_enum" AS ENUM('GLOBAL', 'TENANT', 'PLAN')`);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "message" character varying NOT NULL, "priority" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "displayMode" "public"."announcements_displaymode_enum" NOT NULL DEFAULT 'BANNER', "type" "public"."announcements_type_enum" NOT NULL DEFAULT 'INFO', "targetScope" "public"."announcements_targetscope_enum" NOT NULL DEFAULT 'GLOBAL', "isDismissable" boolean NOT NULL DEFAULT true, "startsAt" TIMESTAMP, "endsAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "announcement_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" integer, "announcement_id" uuid, CONSTRAINT "PK_d24be7309348eba537895dfe0b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "announcement_tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "announcement_id" uuid, CONSTRAINT "PK_d4ec6fe7ab2bdcd9c6aaa848d8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_role_permissions" ("role_id" uuid NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_7b3d2d11cdd9ceb09a39b9d1f06" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_460ea7fd861472b62afa63aeee" ON "platform_role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_51f68c8bbf4a14abafe4710d07" ON "platform_role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "tenant_db_configs" ADD CONSTRAINT "FK_59638e8ce71cd06be80bd37c43b" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_profiles" ADD CONSTRAINT "FK_7755f200fd5c61591cecffa98d0" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_modules" ADD CONSTRAINT "FK_54b5bb2fadb6ada4fe57a9e2701" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_modules" ADD CONSTRAINT "FK_a001196031d22c837d0e45c450e" FOREIGN KEY ("moduleId") REFERENCES "modules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_provisioning_jobs" ADD CONSTRAINT "FK_f3868b220b3177a499e36f3a2dc" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_provisioning_logs" ADD CONSTRAINT "FK_c6fe417e20a8118636d8bbce2fd" FOREIGN KEY ("job_id") REFERENCES "tenant_provisioning_jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_geo_policies" ADD CONSTRAINT "FK_602f1bfc60fb24dedaa6fbe09a3" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_settings" ADD CONSTRAINT "FK_a6abc1c3ed0df635955fc852f1c" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_themes" ADD CONSTRAINT "FK_b1c6aaa6ddcc8ff38da4496cec5" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_limits" ADD CONSTRAINT "FK_1e1c9d21c61a1e815de9591b2fb" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_f6ac03431c311ccb8bbd7d3af18" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7536cba909dd7584a4640cad7d5" FOREIGN KEY ("planId") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_addons" ADD CONSTRAINT "FK_a6967de14fe6bf60070019bea34" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_addons" ADD CONSTRAINT "FK_a75c88d555c47aec5dd4736829a" FOREIGN KEY ("addon_id") REFERENCES "addons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "platform_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_users" ADD CONSTRAINT "FK_b4a968ef87bd13f41af1ea94fc3" FOREIGN KEY ("role_id") REFERENCES "platform_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "states" ADD CONSTRAINT "FK_f3bbd0bc19bb6d8a887add08461" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_440f531f452dcc4389d201b9d4b" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" ADD CONSTRAINT "FK_e94fa427d3da279450dba6f4aa6" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cities" ADD CONSTRAINT "FK_1229b56aa12cae674b824fccd13" FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_110bb0d32b7f65be46be37e2577" FOREIGN KEY ("actorId") REFERENCES "platform_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_38cc2ea20240678a35991d9f676" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_40bd4946a00669c5fb7e6d972f0" FOREIGN KEY ("created_by") REFERENCES "platform_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_plans" ADD CONSTRAINT "FK_1eafe016fcd746622d8bbe96cb1" FOREIGN KEY ("announcement_id") REFERENCES "announcements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_plans" ADD CONSTRAINT "FK_eb835f29610db8ce7aa619f1915" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_tenants" ADD CONSTRAINT "FK_e59896f0500bd6711f71443c6c7" FOREIGN KEY ("announcement_id") REFERENCES "announcements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_tenants" ADD CONSTRAINT "FK_2b9ad4d85303289a0d85af85f74" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_role_permissions" ADD CONSTRAINT "FK_460ea7fd861472b62afa63aeee2" FOREIGN KEY ("role_id") REFERENCES "platform_roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "platform_role_permissions" ADD CONSTRAINT "FK_51f68c8bbf4a14abafe4710d07f" FOREIGN KEY ("permission_id") REFERENCES "platform_permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "platform_role_permissions" DROP CONSTRAINT "FK_51f68c8bbf4a14abafe4710d07f"`);
        await queryRunner.query(`ALTER TABLE "platform_role_permissions" DROP CONSTRAINT "FK_460ea7fd861472b62afa63aeee2"`);
        await queryRunner.query(`ALTER TABLE "announcement_tenants" DROP CONSTRAINT "FK_2b9ad4d85303289a0d85af85f74"`);
        await queryRunner.query(`ALTER TABLE "announcement_tenants" DROP CONSTRAINT "FK_e59896f0500bd6711f71443c6c7"`);
        await queryRunner.query(`ALTER TABLE "announcement_plans" DROP CONSTRAINT "FK_eb835f29610db8ce7aa619f1915"`);
        await queryRunner.query(`ALTER TABLE "announcement_plans" DROP CONSTRAINT "FK_1eafe016fcd746622d8bbe96cb1"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_40bd4946a00669c5fb7e6d972f0"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_38cc2ea20240678a35991d9f676"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_110bb0d32b7f65be46be37e2577"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP CONSTRAINT "FK_1229b56aa12cae674b824fccd13"`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" DROP CONSTRAINT "FK_e94fa427d3da279450dba6f4aa6"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_440f531f452dcc4389d201b9d4b"`);
        await queryRunner.query(`ALTER TABLE "states" DROP CONSTRAINT "FK_f3bbd0bc19bb6d8a887add08461"`);
        await queryRunner.query(`ALTER TABLE "platform_users" DROP CONSTRAINT "FK_b4a968ef87bd13f41af1ea94fc3"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "subscription_addons" DROP CONSTRAINT "FK_a75c88d555c47aec5dd4736829a"`);
        await queryRunner.query(`ALTER TABLE "subscription_addons" DROP CONSTRAINT "FK_a6967de14fe6bf60070019bea34"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7536cba909dd7584a4640cad7d5"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_f6ac03431c311ccb8bbd7d3af18"`);
        await queryRunner.query(`ALTER TABLE "plan_limits" DROP CONSTRAINT "FK_1e1c9d21c61a1e815de9591b2fb"`);
        await queryRunner.query(`ALTER TABLE "tenant_themes" DROP CONSTRAINT "FK_b1c6aaa6ddcc8ff38da4496cec5"`);
        await queryRunner.query(`ALTER TABLE "tenant_settings" DROP CONSTRAINT "FK_a6abc1c3ed0df635955fc852f1c"`);
        await queryRunner.query(`ALTER TABLE "tenant_geo_policies" DROP CONSTRAINT "FK_602f1bfc60fb24dedaa6fbe09a3"`);
        await queryRunner.query(`ALTER TABLE "tenant_provisioning_logs" DROP CONSTRAINT "FK_c6fe417e20a8118636d8bbce2fd"`);
        await queryRunner.query(`ALTER TABLE "tenant_provisioning_jobs" DROP CONSTRAINT "FK_f3868b220b3177a499e36f3a2dc"`);
        await queryRunner.query(`ALTER TABLE "tenant_modules" DROP CONSTRAINT "FK_a001196031d22c837d0e45c450e"`);
        await queryRunner.query(`ALTER TABLE "tenant_modules" DROP CONSTRAINT "FK_54b5bb2fadb6ada4fe57a9e2701"`);
        await queryRunner.query(`ALTER TABLE "tenant_profiles" DROP CONSTRAINT "FK_7755f200fd5c61591cecffa98d0"`);
        await queryRunner.query(`ALTER TABLE "tenant_db_configs" DROP CONSTRAINT "FK_59638e8ce71cd06be80bd37c43b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51f68c8bbf4a14abafe4710d07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_460ea7fd861472b62afa63aeee"`);
        await queryRunner.query(`DROP TABLE "platform_role_permissions"`);
        await queryRunner.query(`DROP TABLE "announcement_tenants"`);
        await queryRunner.query(`DROP TABLE "announcement_plans"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_targetscope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_displaymode_enum"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_actortype_enum"`);
        await queryRunner.query(`DROP TABLE "cities"`);
        await queryRunner.query(`DROP TABLE "invoice_payments"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "states"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31d60a54633e88225b40081e18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa1376321185575cf2226b1491"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP TABLE "platform_permissions"`);
        await queryRunner.query(`DROP TABLE "platform_roles"`);
        await queryRunner.query(`DROP TABLE "platform_users"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "subscription_addons"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_collectiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_paymentmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingmodel_enum"`);
        await queryRunner.query(`DROP TABLE "addons"`);
        await queryRunner.query(`DROP TABLE "plan_limits"`);
        await queryRunner.query(`DROP TYPE "public"."plan_limits_limitkey_enum"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TABLE "tenant_themes"`);
        await queryRunner.query(`DROP TABLE "tenant_settings"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_settings_baselocale_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_settings_baseuom_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_settings_currency_enum"`);
        await queryRunner.query(`DROP TABLE "tenant_geo_policies"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_geo_policies_scope_type_enum"`);
        await queryRunner.query(`DROP TABLE "tenant_provisioning_logs"`);
        await queryRunner.query(`DROP TABLE "tenant_provisioning_jobs"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_industrytype_enum"`);
        await queryRunner.query(`DROP TABLE "tenant_modules"`);
        await queryRunner.query(`DROP TABLE "modules"`);
        await queryRunner.query(`DROP TABLE "tenant_profiles"`);
        await queryRunner.query(`DROP TABLE "tenant_db_configs"`);
    }

}
