import { MigrationInterface, QueryRunner } from "typeorm";

export class TenantDb1780311255416 implements MigrationInterface {
    name = 'TenantDb1780311255416'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."chart_of_accounts_accountkind_enum" AS ENUM('SYSTEM', 'BUSINESS', 'PARTY_RECEIVABLE', 'PARTY_PAYABLE', 'PRODUCT_CATEGORY', 'PRODUCT_SUB_CATEGORY', 'PRODUCT_INVENTORY')`);
        await queryRunner.query(`CREATE TABLE "chart_of_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "partyId" uuid, "productCategoryId" uuid, "productSubCategoryId" uuid, "productId" uuid, "accountKind" "public"."chart_of_accounts_accountkind_enum" NOT NULL DEFAULT 'SYSTEM', "name" character varying NOT NULL, "code" character varying NOT NULL, "parentCode" character varying, "isPostable" boolean NOT NULL DEFAULT true, "level1" integer NOT NULL DEFAULT '0', "level2" integer NOT NULL DEFAULT '0', "level3" integer NOT NULL DEFAULT '0', "level4" integer NOT NULL DEFAULT '0', "level5" integer NOT NULL DEFAULT '0', "level6" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_467c08a2efc78393c647da32bac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1df35b3ae00677b6d3b960868e" ON "chart_of_accounts" ("businessId", "accountKind") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b7eaea2fa2f3bcc84ad9aaf92" ON "chart_of_accounts" ("businessId", "partyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a258809c85f6e8949b3920bf09" ON "chart_of_accounts" ("businessId", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."sale_returns_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "sale_returns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "saleInvoiceId" uuid NOT NULL, "returnNumber" character varying NOT NULL, "returnDate" TIMESTAMP NOT NULL, "returnReason" character varying NOT NULL, "status" "public"."sale_returns_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ec0e8c65946664439f27e8a1d21" UNIQUE ("returnNumber"), CONSTRAINT "PK_0dacb97f81ef1ca47f61409f844" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_return_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "saleReturnId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer, "uomId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_87c0813662620cbb412d65c0cc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "deliveryNoteId" uuid NOT NULL, "customerId" uuid NOT NULL, "saleOrderId" uuid NOT NULL, "invoiceNumber" character varying NOT NULL, "invoiceDate" TIMESTAMP NOT NULL, "totalTaxAmount" numeric(18,2) NOT NULL, "totalDiscountAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_60e00db29772a98d544fe50f7b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_invoice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "saleInvoiceId" uuid NOT NULL, "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "productFlavourId" integer, "warehouseId" uuid NOT NULL, "quantity" integer NOT NULL, "saleUnitPrice" numeric(18,2) NOT NULL, "discountPercentage" numeric(18,2) NOT NULL, "discountAmount" numeric(18,2) NOT NULL, "taxPercentage" numeric(18,2) NOT NULL, "taxAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_f6ee1370c1e9511ec59ca68118f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "saleOrderId" uuid NOT NULL, "customerId" uuid NOT NULL, "deliveryNoteNumber" character varying NOT NULL, "deliveryNoteDate" TIMESTAMP NOT NULL, "notes" character varying, "deliveryCost" numeric(18,2) NOT NULL, "totalTaxAmount" numeric(18,2) NOT NULL, "totalDiscountAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a15e1b336a427fcbedeb36c9531" UNIQUE ("deliveryNoteNumber"), CONSTRAINT "PK_8ba22b28b7392ac676c680dd5d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_note_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deliveryNoteId" uuid NOT NULL, "saleOrderItemId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer, "uomId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "orderedQuantity" integer NOT NULL, "deliveredQuantity" integer NOT NULL, "saleUnitPrice" numeric(18,2) NOT NULL, "discountPercentage" numeric(18,2) NOT NULL, "discountAmount" numeric(18,2) NOT NULL, "taxPercentage" numeric(18,2) NOT NULL, "taxAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, CONSTRAINT "PK_d0093bd2efb0757f8142f11f027" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sale_orders_orderstatus_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "sale_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "customerId" uuid NOT NULL, "orderNumber" character varying NOT NULL, "orderStatus" "public"."sale_orders_orderstatus_enum" NOT NULL, "orderTotal" numeric(18,2) NOT NULL, "deliveryCost" numeric(18,2) NOT NULL DEFAULT '0', "taxPercentage" numeric(18,2) NOT NULL DEFAULT '0', "taxAmount" numeric(18,2) NOT NULL DEFAULT '0', "discountPercentage" numeric(18,2) NOT NULL DEFAULT '0', "discountAmount" numeric(18,2) NOT NULL DEFAULT '0', "totalAmount" numeric(18,2) NOT NULL DEFAULT '0', "notes" character varying, "createdBy" uuid, "orderDate" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ca1959beef162c2ccace1481cec" UNIQUE ("orderNumber"), CONSTRAINT "PK_ba301b7939d3333e8821ff92637" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "saleOrderId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer, "uomId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "purchaseUnitPrice" numeric(18,2) NOT NULL, "saleMarginAmount" numeric(18,2) NOT NULL, "saleMarginPercentage" numeric(18,2) NOT NULL, "quantity" integer NOT NULL, "discountPercentage" numeric(18,2) NOT NULL DEFAULT '0', "discountAmount" numeric(18,2) NOT NULL DEFAULT '0', "totalAmount" numeric(18,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c46724b3d93b4c233ca288871a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_quotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "quotationNumber" character varying NOT NULL, "vendorId" uuid NOT NULL, "quotationDate" TIMESTAMP NOT NULL, "notes" character varying, "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_92b2b397a788a1013a508ca5488" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_quotation_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseQuotationId" uuid NOT NULL, "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a532500070b8d3c171f91bce2ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "batchs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "vendorId" uuid NOT NULL, "batchNumber" character varying NOT NULL, "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "quantity" integer NOT NULL, "purchaseUnitPrice" numeric(18,2) NOT NULL, "saleUnitMarginAmount" numeric(18,2) NOT NULL, "saleUnitMarginPercentage" numeric(18,2) NOT NULL, "batchDate" TIMESTAMP NOT NULL, "expiryDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_570ffed5b5836cb530c89db9898" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "quantityAvailable" integer NOT NULL, "quantityOnHand" integer NOT NULL, "quantityReserved" integer NOT NULL, "quantityDamaged" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_4c0d249ce58f9a559eb7df31b23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_stock_balances_active_business_warehouse_product_uom" ON "stock_balances" ("businessId", "warehouseId", "productId", "uomId") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "quantity" integer NOT NULL, "movementType" character varying NOT NULL, "referenceType" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_returns_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "purchase_returns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "purchaseInvoiceId" uuid NOT NULL, "returnNumber" character varying NOT NULL, "returnDate" TIMESTAMP NOT NULL, "returnReason" character varying NOT NULL, "status" "public"."purchase_returns_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_448bb11c381cb6275453a448f32" UNIQUE ("returnNumber"), CONSTRAINT "PK_cc2ea54a32938fc38a4e5442330" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_return_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseReturnId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer, "uomId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b392d1493da8d20117cc5f0c135" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase-invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "grnId" uuid NOT NULL, "vendorId" uuid NOT NULL, "purchaseOrderId" uuid NOT NULL, "invoiceNumber" character varying NOT NULL, "invoiceDate" TIMESTAMP NOT NULL, "totalTaxAmount" numeric(18,2) NOT NULL, "totalDiscountAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_fe6ae1dad3a6567ba45f2ed0b50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase-invoice-items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseInvoiceId" uuid NOT NULL, "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "productFlavourId" integer, "quantity" integer NOT NULL, "purchaseUnitPrice" numeric(18,2) NOT NULL, "discountPercentage" numeric(18,2) NOT NULL, "discountAmount" numeric(18,2) NOT NULL, "taxPercentage" numeric(18,2) NOT NULL, "taxAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_209b03d96b38dcc9e287f53f5ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_quotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "quotationNumber" character varying NOT NULL, "customerId" uuid NOT NULL, "quotationDate" TIMESTAMP NOT NULL, "notes" character varying, "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_050d87e7d738e82af4f628d8331" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_quotation_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "saleQuotationId" uuid NOT NULL, "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee53b2f3670efd4a61fcf3cf434" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "chartOfAccountId" uuid, "created_by" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_sub_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "businessId" uuid NOT NULL, "categoryId" uuid NOT NULL, "chartOfAccountId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e097414635e4e779f66aa98e0a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "flavours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_58d10322f711a67c1c70a8d0820" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "uoms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying NOT NULL, "is_base" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f207a792064e3032c8fe3922b22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f2b98a8f25bd37b19c8356ec659" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_batchpickstrategy_enum" AS ENUM('FIFO', 'LIFO', 'AVG_COST')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "categoryId" uuid NOT NULL, "subCategoryId" uuid NOT NULL, "skuCode" character varying NOT NULL, "barcode" character varying, "name" character varying NOT NULL, "batchPickStrategy" "public"."products_batchpickstrategy_enum" NOT NULL DEFAULT 'LIFO', "hsCode" character varying, "description" character varying, "brandId" uuid, "image" character varying, "chartOfAccountId" uuid, "isActive" boolean NOT NULL DEFAULT true, "isDelete" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" uuid, CONSTRAINT "UQ_65ac74fb678576a4a9865d7eaf6" UNIQUE ("skuCode"), CONSTRAINT "UQ_adfc522baf9d9b19cd7d9461b7e" UNIQUE ("barcode"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_flavours" ("id" SERIAL NOT NULL, "productId" uuid NOT NULL, "flavourId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_52de19df846c67e8a3614664d5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_pricings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "purchaseUnitPrice" numeric(18,2) NOT NULL, "saleUnitMarginAmount" numeric(18,2) NOT NULL, "saleUnitMarginPercentage" numeric(18,2) NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b02e2444e19a69760718a1c6eeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_pricing_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "productId" uuid NOT NULL, "productPricingId" uuid NOT NULL, "startDate" TIMESTAMP NOT NULL, "status" character varying NOT NULL, "purchaseUnitPrice" character varying NOT NULL, "saleUnitPrice" character varying NOT NULL, "quantity" integer NOT NULL, "errorMessage" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e12966075c7f49d527c8772ae8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_orderstatus_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "orderNumber" character varying NOT NULL, "warehouseId" uuid NOT NULL, "vendorId" uuid NOT NULL, "orderStatus" "public"."purchase_orders_orderstatus_enum" NOT NULL, "orderTotal" numeric(18,2) NOT NULL, "deliveryCost" numeric(18,2) NOT NULL DEFAULT '0', "taxPercentage" numeric(18,2) NOT NULL, "taxAmount" numeric(18,2) NOT NULL, "discountPercentage" numeric(18,2) NOT NULL, "discountAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "notes" character varying, "createdBy" uuid NOT NULL, "orderDate" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0a4ef1738b13da938b62393dc04" UNIQUE ("orderNumber"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseOrderId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer, "uomId" uuid NOT NULL, "purchaseUnitPrice" numeric(18,2) NOT NULL, "saleUnitMarginAmount" numeric(18,2) NOT NULL, "saleUnitMarginPercentage" numeric(18,2) NOT NULL, "quantity" integer NOT NULL, "discountPercentage" numeric(18,2) NOT NULL DEFAULT '0', "discountAmount" numeric(18,2) NOT NULL DEFAULT '0', "totalAmount" numeric(18,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."parties_type_enum" AS ENUM('CUSTOMER', 'VENDOR', 'BOTH')`);
        await queryRunner.query(`CREATE TYPE "public"."parties_partyclass_enum" AS ENUM('A', 'B', 'C')`);
        await queryRunner.query(`CREATE TABLE "parties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "code" character varying(50) NOT NULL, "receivableAccountId" uuid, "payableAccountId" uuid, "name" character varying(200) NOT NULL, "type" "public"."parties_type_enum" NOT NULL, "partyClass" "public"."parties_partyclass_enum", "email" character varying(150), "phone" character varying(50), "whatsAppNumber" character varying(50), "alternatePhone" character varying(50), "ntnNumber" character varying(50), "strnNumber" character varying(50), "cnic" character varying(20), "taxNumber" character varying(50), "address" text, "countryId" character varying, "stateId" character varying, "cityId" character varying, "creditLimit" numeric(18,2), "payableOpeningBalance" numeric(18,2) NOT NULL DEFAULT '0', "receivableOpeningBalance" numeric(18,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_da698299dca60d55f0050dde935" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_18bcff4d4f291cadef07331a46" ON "parties" ("businessId", "code") `);
        await queryRunner.query(`CREATE TABLE "goods_receive_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseOrderId" uuid NOT NULL, "businessId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "vendorId" uuid NOT NULL, "grnNumber" character varying NOT NULL, "grnDate" TIMESTAMP NOT NULL, "notes" character varying, "deliveryCost" numeric(18,2) NOT NULL, "createdBy" uuid NOT NULL, "totalTaxAmount" numeric(18,2) NOT NULL, "totalDiscountAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_d5ca35e2597bbf0c9ef55b2592c" UNIQUE ("grnNumber"), CONSTRAINT "PK_b9c5ca4ad97a32031e8ccb555b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grn_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "grnId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer, "uomId" uuid NOT NULL, "orderedQuantity" integer NOT NULL, "receivedQuantity" integer NOT NULL, "purchaseUnitPrice" numeric(18,2) NOT NULL, "saleUnitMarginAmount" numeric(18,2) NOT NULL, "saleUnitMarginPercentage" numeric(18,2) NOT NULL, "discountPercentage" numeric(18,2) NOT NULL, "discountAmount" numeric(18,2) NOT NULL, "taxPercentage" numeric(18,2) NOT NULL, "taxAmount" numeric(18,2) NOT NULL, "totalAmount" numeric(18,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f6a5723d6cf2d0c66985fb833c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying(150) NOT NULL, "email" character varying(150) NOT NULL, "password" character varying(255), "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "phone" character varying, "avatar" character varying, "cnic" character varying, "address" character varying, "fcmToken" character varying, "deviceId" character varying, "appVersion" character varying, "isSuperAdmin" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_1f7a2b11e29b1422a2622beab36" UNIQUE ("code"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(150) NOT NULL, "name" character varying(150) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_017943867ed5ceef9c03edd974" ON "permissions" ("key") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d430a02aad006d8a70f3acd7d0" ON "role_permissions" ("roleId", "permissionId") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" character varying(255), "isSystemRole" boolean NOT NULL DEFAULT false, "status" "public"."roles_status_enum" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."user_businesses_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "user_businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "businessId" uuid NOT NULL, "roleId" uuid NOT NULL, "status" "public"."user_businesses_status_enum" NOT NULL DEFAULT 'ACTIVE', "permissionVersion" integer NOT NULL DEFAULT '1', "lastSelectedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_a79c8d582e8d7582e92dac57beb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_618d4e9c71657ed503e27eee42" ON "user_businesses" ("userId", "businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_referencetype_enum" AS ENUM('OPENING_BALANCE', 'GRN', 'PURCHASE_INVOICE', 'PURCHASE_RETURN', 'PURCHASE_RETURN_VOUCHER', 'PAYMENT_VOUCHER', 'DELIVERY_NOTE', 'SALE_ORDER', 'SALE_INVOICE', 'SALE_RETURN', 'SALE_RETURN_VOUCHER', 'RECEIPT_VOUCHER', 'EXPENSE_VOUCHER', 'CONTRA_VOUCHER', 'JOURNAL_VOUCHER', 'STOCK_ADJUSTMENT', 'STOCK_DAMAGE', 'DAMAGE_WRITE_OFF', 'PAYSLIP', 'SALARY_VOUCHER', 'BUSINESS_LOAN', 'LOAN_RECEIPT_VOUCHER', 'LOAN_PAYMENT_VOUCHER', 'INTEREST_ACCRUAL_VOUCHER')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "chartOfAccountId" uuid NOT NULL, "referenceType" "public"."transactions_referencetype_enum" NOT NULL, "referenceId" uuid, "transactionDate" date NOT NULL, "description" text, "debitAmount" numeric(18,2), "creditAmount" numeric(18,2), "currentBalance" numeric(18,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c65ec697ef3315ad81d557aa0" ON "transactions" ("businessId", "chartOfAccountId", "transactionDate", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b6b916208bd8d9473df7b4422" ON "transactions" ("businessId", "referenceType", "referenceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b65f1f19f883ca951a7760051" ON "transactions" ("businessId", "chartOfAccountId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_abf59c6a96fdcb74af93a808f7" ON "transactions" ("businessId", "chartOfAccountId") `);
        await queryRunner.query(`CREATE TYPE "public"."businesses_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "code" character varying(20) NOT NULL, "legalName" character varying(180), "logo" character varying, "currency" character varying(10) NOT NULL DEFAULT 'PKR', "phone" character varying(50), "address" text, "financialYearStart" date, "financialYearEnd" date, "status" "public"."businesses_status_enum" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_bc1bf63498dd2368ce3dc8686e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_31e657169754a8feaa08c17bc2" ON "businesses" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6c9b65a09431edc42068186ba0" ON "businesses" ("code") `);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "businessId" uuid NOT NULL, "code" character varying NOT NULL, "address" character varying NOT NULL, "cityId" character varying NOT NULL, "stateId" character varying NOT NULL, "countryId" character varying NOT NULL, "zipCode" character varying, "phone" character varying, "email" character varying, "website" character varying, "contactPersonName" character varying, "contactPersonPhone" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sale_return_vouchers_paymentmethod_enum" AS ENUM('CASH', 'CHEQUE', 'TRANSFER', 'ONLINE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."sale_return_vouchers_status_enum" AS ENUM('PENDING', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "sale_return_vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voucherNumber" character varying NOT NULL, "invoiceId" character varying, "partyId" uuid NOT NULL, "accId" uuid NOT NULL, "paymentMethod" "public"."sale_return_vouchers_paymentmethod_enum" NOT NULL, "chequeNumber" character varying, "chequeDate" TIMESTAMP, "bankName" character varying, "paymentDate" TIMESTAMP NOT NULL, "paymentAmount" numeric(20,2) NOT NULL, "remarks" character varying, "createdBy" uuid, "status" "public"."sale_return_vouchers_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_112945e0c889a533102d76e2b08" UNIQUE ("voucherNumber"), CONSTRAINT "PK_42eebb5be0003a9478aae6d10c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sale_vouchers_paymentmethod_enum" AS ENUM('CASH', 'CHEQUE', 'TRANSFER', 'ONLINE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."sale_vouchers_status_enum" AS ENUM('PENDING', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "sale_vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voucherNumber" character varying NOT NULL, "partyId" uuid NOT NULL, "accId" uuid NOT NULL, "paymentMethod" "public"."sale_vouchers_paymentmethod_enum" NOT NULL, "chequeNumber" character varying, "chequeDate" TIMESTAMP, "bankName" character varying, "paymentDate" TIMESTAMP NOT NULL, "paymentAmount" numeric(20,2) NOT NULL, "remarks" character varying, "createdBy" uuid, "status" "public"."sale_vouchers_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_53ed0aec2b796c54d9d0f9488fa" UNIQUE ("voucherNumber"), CONSTRAINT "PK_5f255d914155fee4f6fa8c5b54d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_vouchers_paymentmethod_enum" AS ENUM('CASH', 'CHEQUE', 'TRANSFER', 'ONLINE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_vouchers_status_enum" AS ENUM('PENDING', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "purchase_vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voucherNumber" character varying NOT NULL, "partyId" uuid NOT NULL, "accId" uuid NOT NULL, "paymentMethod" "public"."purchase_vouchers_paymentmethod_enum" NOT NULL, "chequeNumber" character varying, "chequeDate" TIMESTAMP, "bankName" character varying, "paymentDate" TIMESTAMP NOT NULL, "paymentAmount" numeric(20,2) NOT NULL, "remarks" character varying, "createdBy" uuid, "status" "public"."purchase_vouchers_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2fbc217154af05146cafb28d79d" UNIQUE ("voucherNumber"), CONSTRAINT "PK_a67ad8bfe3cbebe613a7d0e2ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_return_vouchers_paymentmethod_enum" AS ENUM('CASH', 'CHEQUE', 'TRANSFER', 'ONLINE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_return_vouchers_status_enum" AS ENUM('PENDING', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "purchase_return_vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voucherNumber" character varying NOT NULL, "invoiceId" character varying, "partyId" uuid NOT NULL, "accId" uuid NOT NULL, "paymentMethod" "public"."purchase_return_vouchers_paymentmethod_enum" NOT NULL, "chequeNumber" character varying, "chequeDate" TIMESTAMP, "bankName" character varying, "paymentDate" TIMESTAMP NOT NULL, "paymentAmount" numeric(20,2) NOT NULL, "remarks" character varying, "createdBy" uuid, "status" "public"."purchase_return_vouchers_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b7a5036ea8ca6c078adbbc03f27" UNIQUE ("voucherNumber"), CONSTRAINT "PK_ac9e3689bb00eef1d6cc0ac8959" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "businessId" uuid NOT NULL, "title" text NOT NULL, "message" text NOT NULL, "type" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."loans_status_enum" AS ENUM('DRAFT', 'APPROVED', 'ACTIVE', 'PARTIALLY_PAID', 'CLOSED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loanNumber" character varying NOT NULL, "loanAccId" uuid NOT NULL, "receivingAccId" uuid NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "principalAmount" numeric(20,2) NOT NULL, "status" "public"."loans_status_enum" NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_85a8039b5fa766f174be9259afe" UNIQUE ("loanNumber"), CONSTRAINT "PK_5c6942c1e13e4de135c5203ee61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expense_vouchers_paymentmethod_enum" AS ENUM('CASH', 'CHEQUE', 'TRANSFER', 'ONLINE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."expense_vouchers_status_enum" AS ENUM('PENDING', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "expense_vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voucherNumber" character varying NOT NULL, "expenseAccId" uuid NOT NULL, "accId" uuid NOT NULL, "paymentMethod" "public"."expense_vouchers_paymentmethod_enum" NOT NULL, "chequeNumber" character varying, "chequeDate" TIMESTAMP, "bankName" character varying, "paymentDate" TIMESTAMP NOT NULL, "paymentAmount" numeric(20,2) NOT NULL, "remarks" character varying, "createdBy" uuid, "status" "public"."expense_vouchers_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3b11dc24b17d9caf99ac23dc47e" UNIQUE ("voucherNumber"), CONSTRAINT "PK_364d488d83ef72cbb7af1694c2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contra_vouchers_paymentmethod_enum" AS ENUM('CASH', 'CHEQUE', 'TRANSFER', 'ONLINE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."contra_vouchers_status_enum" AS ENUM('PENDING', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "contra_vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voucherNumber" character varying NOT NULL, "fromAccId" uuid NOT NULL, "toAccId" uuid NOT NULL, "paymentMethod" "public"."contra_vouchers_paymentmethod_enum" NOT NULL, "chequeNumber" character varying, "chequeDate" TIMESTAMP, "bankName" character varying, "paymentDate" TIMESTAMP NOT NULL, "paymentAmount" numeric(20,2) NOT NULL, "remarks" character varying, "createdBy" uuid, "status" "public"."contra_vouchers_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3025f9202a6359c7192637f762c" UNIQUE ("voucherNumber"), CONSTRAINT "PK_47e28b49efd3414cdb6bab9fb3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assets_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "uploadedById" uuid, "purpose" character varying NOT NULL, "s3Key" character varying NOT NULL, "entityType" character varying, "entityId" character varying, "originalFileName" character varying NOT NULL, "fileExtension" character varying NOT NULL, "fileSize" integer NOT NULL, "status" "public"."assets_status_enum" NOT NULL, "confirmedAt" TIMESTAMP, "attachedAt" TIMESTAMP, "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid, "actorId" uuid, "action" character varying(120) NOT NULL, "description" text, "metadata" jsonb, "jobId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" ADD CONSTRAINT "FK_aef65ea45fb800ed224b252184a" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" ADD CONSTRAINT "FK_85c4d3a6b8e85970fa4965f2e44" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_returns" ADD CONSTRAINT "FK_b429dd40b940116c9f914bb981d" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_returns" ADD CONSTRAINT "FK_59d9530b33ba6ad0e19b626fe0b" FOREIGN KEY ("saleInvoiceId") REFERENCES "sale_invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" ADD CONSTRAINT "FK_b3c0ce7bdc39fb898c63b24c7b8" FOREIGN KEY ("saleReturnId") REFERENCES "sale_returns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" ADD CONSTRAINT "FK_d8a7fcf6b77d7a163e93a9eda84" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" ADD CONSTRAINT "FK_6562b7cdcc2fac9896ae1475bef" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" ADD CONSTRAINT "FK_139689d542150b82059b03f6022" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" ADD CONSTRAINT "FK_47cbeee9bb1918d6ccbf69f67b1" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" ADD CONSTRAINT "FK_611ef49e5cab041fd5cf66f32bc" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" ADD CONSTRAINT "FK_09a8f0df6733db06803082fd3c1" FOREIGN KEY ("deliveryNoteId") REFERENCES "delivery_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" ADD CONSTRAINT "FK_f4408ca7a0f4f8726139a50b290" FOREIGN KEY ("customerId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" ADD CONSTRAINT "FK_9b06101869f1c780a2d8dcf424e" FOREIGN KEY ("saleOrderId") REFERENCES "sale_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" ADD CONSTRAINT "FK_ec18cd532a12496a9808ba82e1a" FOREIGN KEY ("saleInvoiceId") REFERENCES "sale_invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" ADD CONSTRAINT "FK_c8d5c4c5bca5102a35be73efd15" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" ADD CONSTRAINT "FK_9ed9c50bf9f1777b81198955c93" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" ADD CONSTRAINT "FK_ca685ab2ba89229f3609d0b25cd" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" ADD CONSTRAINT "FK_856082495ee393b2998a38ea0fb" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" ADD CONSTRAINT "FK_bc25b0d9a16fcc09c12d4545c66" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" ADD CONSTRAINT "FK_9fff5595e51e293b20661f12cc5" FOREIGN KEY ("saleOrderId") REFERENCES "sale_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" ADD CONSTRAINT "FK_f5c9dbf55d00344cb4593071d2f" FOREIGN KEY ("customerId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" ADD CONSTRAINT "FK_35b0ed2c835914cd6d21cfcfc68" FOREIGN KEY ("deliveryNoteId") REFERENCES "delivery_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" ADD CONSTRAINT "FK_cdf44f5823ae946433680421e5c" FOREIGN KEY ("saleOrderItemId") REFERENCES "sale_order_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" ADD CONSTRAINT "FK_66040889c9dc7425e79a6ff14f6" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" ADD CONSTRAINT "FK_cc9fe0d10943e6fd53230c979af" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" ADD CONSTRAINT "FK_fd7e151b0af86fd326fa03ebdfe" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" ADD CONSTRAINT "FK_ccf4e79a36666676c64e4c606a3" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_ddcd3b01389ae7faa3cb1ab8bd5" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_a7de3c23058d66020d9207b2894" FOREIGN KEY ("customerId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_4f1904438f503dfb4eac2e65cad" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_d49fcbd1de0d711c2c7e98a0e4b" FOREIGN KEY ("saleOrderId") REFERENCES "sale_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_1449ab76dc9e3f75a472539904e" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_8771927a21dd3d9ddc7cbfdd3d0" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_06ae835081995142b1b34d47a68" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_f333a449e9b83a2bf6fe0623dc9" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" ADD CONSTRAINT "FK_da8acd41365587b0603d0034289" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" ADD CONSTRAINT "FK_20909dfcb24e8f531b21b2a2021" FOREIGN KEY ("vendorId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" ADD CONSTRAINT "FK_7b9275375e5d4439c92e957a8d1" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" ADD CONSTRAINT "FK_46b622fbc48deb7fc11b7c50310" FOREIGN KEY ("purchaseQuotationId") REFERENCES "purchase_quotations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" ADD CONSTRAINT "FK_3957498131756bb07ceba105bcd" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" ADD CONSTRAINT "FK_f6c31ba6763d39a8341f25ece26" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batchs" ADD CONSTRAINT "FK_948bf01498198000d8257726ed9" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batchs" ADD CONSTRAINT "FK_5129eca0520e1d2b0d556c85e4e" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batchs" ADD CONSTRAINT "FK_e46db5a3c5fb291e54ed32d9755" FOREIGN KEY ("vendorId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batchs" ADD CONSTRAINT "FK_6480f2eb15e6029e330926beeff" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batchs" ADD CONSTRAINT "FK_0de8894ade80953ab9e9765b42d" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_2919c5a459b716c5ba132a5ad95" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_d949e4488d09dca62fd3561fa90" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_6840607b19b9f629d9c6845f31c" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_1a3cd9020b84899581248eae7ad" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_847ae48018bbd08f4fbbac53006" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_2d118fa925e343f74b7dfe822ec" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_a3acb59db67e977be45e382fc56" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_28dc554de7559b16be2e2a82b15" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_returns" ADD CONSTRAINT "FK_d135977d630439ce5dc85d91416" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_returns" ADD CONSTRAINT "FK_2affe102b7a6e0f943275b98298" FOREIGN KEY ("purchaseInvoiceId") REFERENCES "purchase-invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" ADD CONSTRAINT "FK_7c0ccb18970b1a9ba216b901523" FOREIGN KEY ("purchaseReturnId") REFERENCES "purchase_returns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" ADD CONSTRAINT "FK_78869e46faa7e78b73165000971" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" ADD CONSTRAINT "FK_08b5cead9551c69ddce76e6061c" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" ADD CONSTRAINT "FK_0a25a55f802281ad65a275d2b61" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" ADD CONSTRAINT "FK_2c719b11099d1acb589d47cae88" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" ADD CONSTRAINT "FK_cf327a55ca96b70bfc473322300" FOREIGN KEY ("grnId") REFERENCES "goods_receive_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" ADD CONSTRAINT "FK_f2ae2a830ed12d41c2fcf02cddb" FOREIGN KEY ("vendorId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" ADD CONSTRAINT "FK_47fc2115cd4854d03e038ff514a" FOREIGN KEY ("purchaseOrderId") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" ADD CONSTRAINT "FK_da5b92cdf5f35cb68e067dcc666" FOREIGN KEY ("purchaseInvoiceId") REFERENCES "purchase-invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" ADD CONSTRAINT "FK_5d7d87ef8d3164927d63e2af07d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" ADD CONSTRAINT "FK_f1d9327a381087deb7bdcf5b8cb" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" ADD CONSTRAINT "FK_d6fc9aabb199b147de74a0705d9" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_quotations" ADD CONSTRAINT "FK_80d26f4339ecd910f76d59cddac" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_quotations" ADD CONSTRAINT "FK_f4ccfac20ed75b0da7511981ed8" FOREIGN KEY ("customerId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_quotations" ADD CONSTRAINT "FK_e9e7cb4a3c1381d363403ec1fec" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_quotation_items" ADD CONSTRAINT "FK_be17733aa3a2a45bc27d8035a34" FOREIGN KEY ("saleQuotationId") REFERENCES "sale_quotations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_quotation_items" ADD CONSTRAINT "FK_62df1989575dc4cb228f38160ce" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_quotation_items" ADD CONSTRAINT "FK_082632f4dcb5c5eb005e94108a9" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_408cd327d592771780bb6a759df" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_86848c3b72ae859be3023e9d270" FOREIGN KEY ("chartOfAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_66bf1d237f3576eeae37ac1b2eb" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_sub_categories" ADD CONSTRAINT "FK_e24e05f97fc483cd55da61609d2" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_sub_categories" ADD CONSTRAINT "FK_7cbcc635181ce3544e4f66914de" FOREIGN KEY ("categoryId") REFERENCES "product_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_sub_categories" ADD CONSTRAINT "FK_a9f99b56e255e44d27e5ab6034d" FOREIGN KEY ("chartOfAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flavours" ADD CONSTRAINT "FK_16f79857a5c0071c32470a8d49d" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uoms" ADD CONSTRAINT "FK_9a38c6b48544e6d373a26eadb61" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_brands" ADD CONSTRAINT "FK_889c2ca530ce9e7420d034062d5" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "product_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ad42985fb27aa9016b16ee740ec" FOREIGN KEY ("subCategoryId") REFERENCES "product_sub_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df" FOREIGN KEY ("brandId") REFERENCES "product_brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_1c8a1d758de7da98c3b543d6727" FOREIGN KEY ("chartOfAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_f74bae41998e06cc579f081ea78" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_flavours" ADD CONSTRAINT "FK_a0282b16f9daac2e15112340566" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_flavours" ADD CONSTRAINT "FK_a08a13461af44625ec0bff252f4" FOREIGN KEY ("flavourId") REFERENCES "flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricings" ADD CONSTRAINT "FK_b43a68bd3e947aa98a89f45aa66" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricings" ADD CONSTRAINT "FK_d6c3496a0f0db19c58282f97e2a" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" ADD CONSTRAINT "FK_6092c1cae8cb000f01ac33e7d49" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" ADD CONSTRAINT "FK_2c90c83e94881af1f566f5249e4" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" ADD CONSTRAINT "FK_9674e21a39bdf7d08d5ad247eac" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_526a058859501c706e473d18352" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_f52c798da22c916be5a9e7ac152" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_e04bec5cd5b302470c3ae474e1c" FOREIGN KEY ("vendorId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_c373026da3848c1742a3b38cf71" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_1de7eb246940b05765d2c99a7ec" FOREIGN KEY ("purchaseOrderId") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_f87b1b82a3aff16d1cb5e49a656" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_1ba4373b198ebfb037bbee41c1e" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_ddb317285e379919a9ebc0d011b" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parties" ADD CONSTRAINT "FK_e84e33a64bed346ea260371fdcd" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parties" ADD CONSTRAINT "FK_24b15ab9bfb00d8f0a407110a4b" FOREIGN KEY ("receivableAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parties" ADD CONSTRAINT "FK_5d580c86dc1fbcbf226b32d1f7d" FOREIGN KEY ("payableAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" ADD CONSTRAINT "FK_e78bd8e53d79272bb17ce0118b9" FOREIGN KEY ("purchaseOrderId") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" ADD CONSTRAINT "FK_326f0ef5de4ebbe8c808dcce586" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" ADD CONSTRAINT "FK_a0fd2f1746f8fd2151221d792e1" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" ADD CONSTRAINT "FK_895bdf5c8ae68cbf4f19cc6a987" FOREIGN KEY ("vendorId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" ADD CONSTRAINT "FK_142cddb4fa29bbd3ce20f2bc92e" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grn_items" ADD CONSTRAINT "FK_106b209f935c117cb7f07af84c7" FOREIGN KEY ("grnId") REFERENCES "goods_receive_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grn_items" ADD CONSTRAINT "FK_a43bf15a923e101631a6ed90513" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grn_items" ADD CONSTRAINT "FK_39866a46f4f8582e4f388f9006e" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grn_items" ADD CONSTRAINT "FK_48ecfb46ab338855b6647e92ea3" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_businesses" ADD CONSTRAINT "FK_1a2fd3e163cd1d20912b87bc35c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_businesses" ADD CONSTRAINT "FK_b09272549f21e881f0d6faa0012" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_businesses" ADD CONSTRAINT "FK_b8e35890a97d885996f2adef834" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_9f24c9c8611e077a48a0645e3df" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_37adc61669d5b9414e2495398a9" FOREIGN KEY ("chartOfAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_09b8b9e2811bfd160b328f4a71d" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_vouchers" ADD CONSTRAINT "FK_6a62f70ad9c7a71a54c03666e3e" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_vouchers" ADD CONSTRAINT "FK_8775e70c5b3cc7c5e66b05f0f0e" FOREIGN KEY ("accId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_return_vouchers" ADD CONSTRAINT "FK_e2d9c65cdbf8005dd710f7e33c1" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_vouchers" ADD CONSTRAINT "FK_7b24274839e6b3440b8601dbf91" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_vouchers" ADD CONSTRAINT "FK_b6c454770e1a2498dfed5eb6753" FOREIGN KEY ("accId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_vouchers" ADD CONSTRAINT "FK_1377f23a8c110193b2671c06b7f" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_vouchers" ADD CONSTRAINT "FK_9be213bf4b8a74b1540c96da307" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_vouchers" ADD CONSTRAINT "FK_68748a3fd1ebe94293690e832d7" FOREIGN KEY ("accId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_vouchers" ADD CONSTRAINT "FK_0f8a1d3fd90619ac134648c4558" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_return_vouchers" ADD CONSTRAINT "FK_7c4f7cd02b481f88ef53765b8ac" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_return_vouchers" ADD CONSTRAINT "FK_53621ac44221d711aa00b821b37" FOREIGN KEY ("accId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_return_vouchers" ADD CONSTRAINT "FK_531107c50cc7edd3d0ee38976c0" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_1525681a7e669aaa6b8edf0e256" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_81cb851f9f5766c9d4d240aa809" FOREIGN KEY ("loanAccId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_d4fdb5b73fc52dab161ad03c2ff" FOREIGN KEY ("receivingAccId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_vouchers" ADD CONSTRAINT "FK_709977c7a15eb7961a064286d8d" FOREIGN KEY ("expenseAccId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_vouchers" ADD CONSTRAINT "FK_491730fa112d18c29ce28b94b2c" FOREIGN KEY ("accId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_vouchers" ADD CONSTRAINT "FK_2f6e91149d50129ce50943ef2a6" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contra_vouchers" ADD CONSTRAINT "FK_7173fde2998f6a46636cf877818" FOREIGN KEY ("fromAccId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contra_vouchers" ADD CONSTRAINT "FK_1eb98a5e5eeed6e53ec9d66ac34" FOREIGN KEY ("toAccId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contra_vouchers" ADD CONSTRAINT "FK_928e363f843caab6860ba99c790" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_b9fdc4600fb5785205eb8ebef55" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_5cd9404c1d35a8f6c8480c83ca8" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_110bb0d32b7f65be46be37e2577" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_110bb0d32b7f65be46be37e2577"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_5cd9404c1d35a8f6c8480c83ca8"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_b9fdc4600fb5785205eb8ebef55"`);
        await queryRunner.query(`ALTER TABLE "contra_vouchers" DROP CONSTRAINT "FK_928e363f843caab6860ba99c790"`);
        await queryRunner.query(`ALTER TABLE "contra_vouchers" DROP CONSTRAINT "FK_1eb98a5e5eeed6e53ec9d66ac34"`);
        await queryRunner.query(`ALTER TABLE "contra_vouchers" DROP CONSTRAINT "FK_7173fde2998f6a46636cf877818"`);
        await queryRunner.query(`ALTER TABLE "expense_vouchers" DROP CONSTRAINT "FK_2f6e91149d50129ce50943ef2a6"`);
        await queryRunner.query(`ALTER TABLE "expense_vouchers" DROP CONSTRAINT "FK_491730fa112d18c29ce28b94b2c"`);
        await queryRunner.query(`ALTER TABLE "expense_vouchers" DROP CONSTRAINT "FK_709977c7a15eb7961a064286d8d"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_d4fdb5b73fc52dab161ad03c2ff"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_81cb851f9f5766c9d4d240aa809"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_1525681a7e669aaa6b8edf0e256"`);
        await queryRunner.query(`ALTER TABLE "purchase_return_vouchers" DROP CONSTRAINT "FK_531107c50cc7edd3d0ee38976c0"`);
        await queryRunner.query(`ALTER TABLE "purchase_return_vouchers" DROP CONSTRAINT "FK_53621ac44221d711aa00b821b37"`);
        await queryRunner.query(`ALTER TABLE "purchase_return_vouchers" DROP CONSTRAINT "FK_7c4f7cd02b481f88ef53765b8ac"`);
        await queryRunner.query(`ALTER TABLE "purchase_vouchers" DROP CONSTRAINT "FK_0f8a1d3fd90619ac134648c4558"`);
        await queryRunner.query(`ALTER TABLE "purchase_vouchers" DROP CONSTRAINT "FK_68748a3fd1ebe94293690e832d7"`);
        await queryRunner.query(`ALTER TABLE "purchase_vouchers" DROP CONSTRAINT "FK_9be213bf4b8a74b1540c96da307"`);
        await queryRunner.query(`ALTER TABLE "sale_vouchers" DROP CONSTRAINT "FK_1377f23a8c110193b2671c06b7f"`);
        await queryRunner.query(`ALTER TABLE "sale_vouchers" DROP CONSTRAINT "FK_b6c454770e1a2498dfed5eb6753"`);
        await queryRunner.query(`ALTER TABLE "sale_vouchers" DROP CONSTRAINT "FK_7b24274839e6b3440b8601dbf91"`);
        await queryRunner.query(`ALTER TABLE "sale_return_vouchers" DROP CONSTRAINT "FK_e2d9c65cdbf8005dd710f7e33c1"`);
        await queryRunner.query(`ALTER TABLE "sale_return_vouchers" DROP CONSTRAINT "FK_8775e70c5b3cc7c5e66b05f0f0e"`);
        await queryRunner.query(`ALTER TABLE "sale_return_vouchers" DROP CONSTRAINT "FK_6a62f70ad9c7a71a54c03666e3e"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_09b8b9e2811bfd160b328f4a71d"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_37adc61669d5b9414e2495398a9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_9f24c9c8611e077a48a0645e3df"`);
        await queryRunner.query(`ALTER TABLE "user_businesses" DROP CONSTRAINT "FK_b8e35890a97d885996f2adef834"`);
        await queryRunner.query(`ALTER TABLE "user_businesses" DROP CONSTRAINT "FK_b09272549f21e881f0d6faa0012"`);
        await queryRunner.query(`ALTER TABLE "user_businesses" DROP CONSTRAINT "FK_1a2fd3e163cd1d20912b87bc35c"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "grn_items" DROP CONSTRAINT "FK_48ecfb46ab338855b6647e92ea3"`);
        await queryRunner.query(`ALTER TABLE "grn_items" DROP CONSTRAINT "FK_39866a46f4f8582e4f388f9006e"`);
        await queryRunner.query(`ALTER TABLE "grn_items" DROP CONSTRAINT "FK_a43bf15a923e101631a6ed90513"`);
        await queryRunner.query(`ALTER TABLE "grn_items" DROP CONSTRAINT "FK_106b209f935c117cb7f07af84c7"`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" DROP CONSTRAINT "FK_142cddb4fa29bbd3ce20f2bc92e"`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" DROP CONSTRAINT "FK_895bdf5c8ae68cbf4f19cc6a987"`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" DROP CONSTRAINT "FK_a0fd2f1746f8fd2151221d792e1"`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" DROP CONSTRAINT "FK_326f0ef5de4ebbe8c808dcce586"`);
        await queryRunner.query(`ALTER TABLE "goods_receive_notes" DROP CONSTRAINT "FK_e78bd8e53d79272bb17ce0118b9"`);
        await queryRunner.query(`ALTER TABLE "parties" DROP CONSTRAINT "FK_5d580c86dc1fbcbf226b32d1f7d"`);
        await queryRunner.query(`ALTER TABLE "parties" DROP CONSTRAINT "FK_24b15ab9bfb00d8f0a407110a4b"`);
        await queryRunner.query(`ALTER TABLE "parties" DROP CONSTRAINT "FK_e84e33a64bed346ea260371fdcd"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_ddb317285e379919a9ebc0d011b"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_1ba4373b198ebfb037bbee41c1e"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_f87b1b82a3aff16d1cb5e49a656"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_1de7eb246940b05765d2c99a7ec"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_c373026da3848c1742a3b38cf71"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_e04bec5cd5b302470c3ae474e1c"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_f52c798da22c916be5a9e7ac152"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_526a058859501c706e473d18352"`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" DROP CONSTRAINT "FK_9674e21a39bdf7d08d5ad247eac"`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" DROP CONSTRAINT "FK_2c90c83e94881af1f566f5249e4"`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" DROP CONSTRAINT "FK_6092c1cae8cb000f01ac33e7d49"`);
        await queryRunner.query(`ALTER TABLE "product_pricings" DROP CONSTRAINT "FK_d6c3496a0f0db19c58282f97e2a"`);
        await queryRunner.query(`ALTER TABLE "product_pricings" DROP CONSTRAINT "FK_b43a68bd3e947aa98a89f45aa66"`);
        await queryRunner.query(`ALTER TABLE "product_flavours" DROP CONSTRAINT "FK_a08a13461af44625ec0bff252f4"`);
        await queryRunner.query(`ALTER TABLE "product_flavours" DROP CONSTRAINT "FK_a0282b16f9daac2e15112340566"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_f74bae41998e06cc579f081ea78"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_1c8a1d758de7da98c3b543d6727"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ad42985fb27aa9016b16ee740ec"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f"`);
        await queryRunner.query(`ALTER TABLE "product_brands" DROP CONSTRAINT "FK_889c2ca530ce9e7420d034062d5"`);
        await queryRunner.query(`ALTER TABLE "uoms" DROP CONSTRAINT "FK_9a38c6b48544e6d373a26eadb61"`);
        await queryRunner.query(`ALTER TABLE "flavours" DROP CONSTRAINT "FK_16f79857a5c0071c32470a8d49d"`);
        await queryRunner.query(`ALTER TABLE "product_sub_categories" DROP CONSTRAINT "FK_a9f99b56e255e44d27e5ab6034d"`);
        await queryRunner.query(`ALTER TABLE "product_sub_categories" DROP CONSTRAINT "FK_7cbcc635181ce3544e4f66914de"`);
        await queryRunner.query(`ALTER TABLE "product_sub_categories" DROP CONSTRAINT "FK_e24e05f97fc483cd55da61609d2"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_66bf1d237f3576eeae37ac1b2eb"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_86848c3b72ae859be3023e9d270"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_408cd327d592771780bb6a759df"`);
        await queryRunner.query(`ALTER TABLE "sale_quotation_items" DROP CONSTRAINT "FK_082632f4dcb5c5eb005e94108a9"`);
        await queryRunner.query(`ALTER TABLE "sale_quotation_items" DROP CONSTRAINT "FK_62df1989575dc4cb228f38160ce"`);
        await queryRunner.query(`ALTER TABLE "sale_quotation_items" DROP CONSTRAINT "FK_be17733aa3a2a45bc27d8035a34"`);
        await queryRunner.query(`ALTER TABLE "sale_quotations" DROP CONSTRAINT "FK_e9e7cb4a3c1381d363403ec1fec"`);
        await queryRunner.query(`ALTER TABLE "sale_quotations" DROP CONSTRAINT "FK_f4ccfac20ed75b0da7511981ed8"`);
        await queryRunner.query(`ALTER TABLE "sale_quotations" DROP CONSTRAINT "FK_80d26f4339ecd910f76d59cddac"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" DROP CONSTRAINT "FK_d6fc9aabb199b147de74a0705d9"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" DROP CONSTRAINT "FK_f1d9327a381087deb7bdcf5b8cb"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" DROP CONSTRAINT "FK_5d7d87ef8d3164927d63e2af07d"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoice-items" DROP CONSTRAINT "FK_da5b92cdf5f35cb68e067dcc666"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" DROP CONSTRAINT "FK_47fc2115cd4854d03e038ff514a"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" DROP CONSTRAINT "FK_f2ae2a830ed12d41c2fcf02cddb"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" DROP CONSTRAINT "FK_cf327a55ca96b70bfc473322300"`);
        await queryRunner.query(`ALTER TABLE "purchase-invoices" DROP CONSTRAINT "FK_2c719b11099d1acb589d47cae88"`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" DROP CONSTRAINT "FK_0a25a55f802281ad65a275d2b61"`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" DROP CONSTRAINT "FK_08b5cead9551c69ddce76e6061c"`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" DROP CONSTRAINT "FK_78869e46faa7e78b73165000971"`);
        await queryRunner.query(`ALTER TABLE "purchase_return_items" DROP CONSTRAINT "FK_7c0ccb18970b1a9ba216b901523"`);
        await queryRunner.query(`ALTER TABLE "purchase_returns" DROP CONSTRAINT "FK_2affe102b7a6e0f943275b98298"`);
        await queryRunner.query(`ALTER TABLE "purchase_returns" DROP CONSTRAINT "FK_d135977d630439ce5dc85d91416"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_28dc554de7559b16be2e2a82b15"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_a3acb59db67e977be45e382fc56"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_2d118fa925e343f74b7dfe822ec"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_847ae48018bbd08f4fbbac53006"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_1a3cd9020b84899581248eae7ad"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_6840607b19b9f629d9c6845f31c"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_d949e4488d09dca62fd3561fa90"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_2919c5a459b716c5ba132a5ad95"`);
        await queryRunner.query(`ALTER TABLE "batchs" DROP CONSTRAINT "FK_0de8894ade80953ab9e9765b42d"`);
        await queryRunner.query(`ALTER TABLE "batchs" DROP CONSTRAINT "FK_6480f2eb15e6029e330926beeff"`);
        await queryRunner.query(`ALTER TABLE "batchs" DROP CONSTRAINT "FK_e46db5a3c5fb291e54ed32d9755"`);
        await queryRunner.query(`ALTER TABLE "batchs" DROP CONSTRAINT "FK_5129eca0520e1d2b0d556c85e4e"`);
        await queryRunner.query(`ALTER TABLE "batchs" DROP CONSTRAINT "FK_948bf01498198000d8257726ed9"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" DROP CONSTRAINT "FK_f6c31ba6763d39a8341f25ece26"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" DROP CONSTRAINT "FK_3957498131756bb07ceba105bcd"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" DROP CONSTRAINT "FK_46b622fbc48deb7fc11b7c50310"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" DROP CONSTRAINT "FK_7b9275375e5d4439c92e957a8d1"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" DROP CONSTRAINT "FK_20909dfcb24e8f531b21b2a2021"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" DROP CONSTRAINT "FK_da8acd41365587b0603d0034289"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_f333a449e9b83a2bf6fe0623dc9"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_06ae835081995142b1b34d47a68"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_8771927a21dd3d9ddc7cbfdd3d0"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_1449ab76dc9e3f75a472539904e"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_d49fcbd1de0d711c2c7e98a0e4b"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_4f1904438f503dfb4eac2e65cad"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_a7de3c23058d66020d9207b2894"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_ddcd3b01389ae7faa3cb1ab8bd5"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" DROP CONSTRAINT "FK_ccf4e79a36666676c64e4c606a3"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" DROP CONSTRAINT "FK_fd7e151b0af86fd326fa03ebdfe"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" DROP CONSTRAINT "FK_cc9fe0d10943e6fd53230c979af"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" DROP CONSTRAINT "FK_66040889c9dc7425e79a6ff14f6"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" DROP CONSTRAINT "FK_cdf44f5823ae946433680421e5c"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_items" DROP CONSTRAINT "FK_35b0ed2c835914cd6d21cfcfc68"`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" DROP CONSTRAINT "FK_f5c9dbf55d00344cb4593071d2f"`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" DROP CONSTRAINT "FK_9fff5595e51e293b20661f12cc5"`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" DROP CONSTRAINT "FK_bc25b0d9a16fcc09c12d4545c66"`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" DROP CONSTRAINT "FK_856082495ee393b2998a38ea0fb"`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" DROP CONSTRAINT "FK_ca685ab2ba89229f3609d0b25cd"`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" DROP CONSTRAINT "FK_9ed9c50bf9f1777b81198955c93"`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" DROP CONSTRAINT "FK_c8d5c4c5bca5102a35be73efd15"`);
        await queryRunner.query(`ALTER TABLE "sale_invoice_items" DROP CONSTRAINT "FK_ec18cd532a12496a9808ba82e1a"`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" DROP CONSTRAINT "FK_9b06101869f1c780a2d8dcf424e"`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" DROP CONSTRAINT "FK_f4408ca7a0f4f8726139a50b290"`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" DROP CONSTRAINT "FK_09a8f0df6733db06803082fd3c1"`);
        await queryRunner.query(`ALTER TABLE "sale_invoices" DROP CONSTRAINT "FK_611ef49e5cab041fd5cf66f32bc"`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" DROP CONSTRAINT "FK_47cbeee9bb1918d6ccbf69f67b1"`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" DROP CONSTRAINT "FK_139689d542150b82059b03f6022"`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" DROP CONSTRAINT "FK_6562b7cdcc2fac9896ae1475bef"`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" DROP CONSTRAINT "FK_d8a7fcf6b77d7a163e93a9eda84"`);
        await queryRunner.query(`ALTER TABLE "sale_return_items" DROP CONSTRAINT "FK_b3c0ce7bdc39fb898c63b24c7b8"`);
        await queryRunner.query(`ALTER TABLE "sale_returns" DROP CONSTRAINT "FK_59d9530b33ba6ad0e19b626fe0b"`);
        await queryRunner.query(`ALTER TABLE "sale_returns" DROP CONSTRAINT "FK_b429dd40b940116c9f914bb981d"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" DROP CONSTRAINT "FK_85c4d3a6b8e85970fa4965f2e44"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" DROP CONSTRAINT "FK_aef65ea45fb800ed224b252184a"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_status_enum"`);
        await queryRunner.query(`DROP TABLE "contra_vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."contra_vouchers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."contra_vouchers_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "expense_vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."expense_vouchers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expense_vouchers_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "loans"`);
        await queryRunner.query(`DROP TYPE "public"."loans_status_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "purchase_return_vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_return_vouchers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_return_vouchers_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_vouchers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_vouchers_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "sale_vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."sale_vouchers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sale_vouchers_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "sale_return_vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."sale_return_vouchers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sale_return_vouchers_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c9b65a09431edc42068186ba0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31e657169754a8feaa08c17bc2"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abf59c6a96fdcb74af93a808f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b65f1f19f883ca951a7760051"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b6b916208bd8d9473df7b4422"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c65ec697ef3315ad81d557aa0"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_referencetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_618d4e9c71657ed503e27eee42"`);
        await queryRunner.query(`DROP TABLE "user_businesses"`);
        await queryRunner.query(`DROP TYPE "public"."user_businesses_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d430a02aad006d8a70f3acd7d0"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017943867ed5ceef9c03edd974"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "grn_items"`);
        await queryRunner.query(`DROP TABLE "goods_receive_notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18bcff4d4f291cadef07331a46"`);
        await queryRunner.query(`DROP TABLE "parties"`);
        await queryRunner.query(`DROP TYPE "public"."parties_partyclass_enum"`);
        await queryRunner.query(`DROP TYPE "public"."parties_type_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_orderstatus_enum"`);
        await queryRunner.query(`DROP TABLE "product_pricing_jobs"`);
        await queryRunner.query(`DROP TABLE "product_pricings"`);
        await queryRunner.query(`DROP TABLE "product_flavours"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_batchpickstrategy_enum"`);
        await queryRunner.query(`DROP TABLE "product_brands"`);
        await queryRunner.query(`DROP TABLE "uoms"`);
        await queryRunner.query(`DROP TABLE "flavours"`);
        await queryRunner.query(`DROP TABLE "product_sub_categories"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP TABLE "sale_quotation_items"`);
        await queryRunner.query(`DROP TABLE "sale_quotations"`);
        await queryRunner.query(`DROP TABLE "purchase-invoice-items"`);
        await queryRunner.query(`DROP TABLE "purchase-invoices"`);
        await queryRunner.query(`DROP TABLE "purchase_return_items"`);
        await queryRunner.query(`DROP TABLE "purchase_returns"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_returns_status_enum"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_balances_active_business_warehouse_product_uom"`);
        await queryRunner.query(`DROP TABLE "stock_balances"`);
        await queryRunner.query(`DROP TABLE "batchs"`);
        await queryRunner.query(`DROP TABLE "purchase_quotation_items"`);
        await queryRunner.query(`DROP TABLE "purchase_quotations"`);
        await queryRunner.query(`DROP TABLE "sale_order_items"`);
        await queryRunner.query(`DROP TABLE "sale_orders"`);
        await queryRunner.query(`DROP TYPE "public"."sale_orders_orderstatus_enum"`);
        await queryRunner.query(`DROP TABLE "delivery_note_items"`);
        await queryRunner.query(`DROP TABLE "delivery_notes"`);
        await queryRunner.query(`DROP TABLE "sale_invoice_items"`);
        await queryRunner.query(`DROP TABLE "sale_invoices"`);
        await queryRunner.query(`DROP TABLE "sale_return_items"`);
        await queryRunner.query(`DROP TABLE "sale_returns"`);
        await queryRunner.query(`DROP TYPE "public"."sale_returns_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a258809c85f6e8949b3920bf09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b7eaea2fa2f3bcc84ad9aaf92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df35b3ae00677b6d3b960868e"`);
        await queryRunner.query(`DROP TABLE "chart_of_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."chart_of_accounts_accountkind_enum"`);
    }

}
