import { MigrationInterface, QueryRunner } from "typeorm";

export class TenantDb1780409897877 implements MigrationInterface {
    name = 'TenantDb1780409897877'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "designations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying(200) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_a0f024b99b1491a03fc421858ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_de99aff7b406a20ad6329a5a82" ON "designations" ("businessId", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."employee_salary_structures_status_enum" AS ENUM('active', 'inactive', 'revised')`);
        await queryRunner.query(`CREATE TABLE "employee_salary_structures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "employeeId" uuid NOT NULL, "payPolicyId" uuid NOT NULL, "effectiveFrom" date NOT NULL, "effectiveTo" date, "basicSalary" numeric(15,2) NOT NULL DEFAULT '0', "grossSalary" numeric(15,2) NOT NULL DEFAULT '0', "totalEarnings" numeric(15,2) NOT NULL DEFAULT '0', "totalDeductions" numeric(15,2) NOT NULL DEFAULT '0', "netSalary" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'PKR', "status" "public"."employee_salary_structures_status_enum" NOT NULL DEFAULT 'active', "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_ddb5bda3965a93766306ed0ca08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_367fb367071532086460f2d9a9" ON "employee_salary_structures" ("businessId", "employeeId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c82a1f5127cd6c2578364a73dd" ON "employee_salary_structures" ("businessId", "employeeId") `);
        await queryRunner.query(`CREATE TYPE "public"."employee_salary_components_componenttype_enum" AS ENUM('earning', 'deduction')`);
        await queryRunner.query(`CREATE TYPE "public"."employee_salary_components_calculationtype_enum" AS ENUM('fixed', 'percentage', 'formula', 'manual')`);
        await queryRunner.query(`CREATE TABLE "employee_salary_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "employeeSalaryStructureId" uuid NOT NULL, "employeeId" uuid NOT NULL, "salaryComponentId" uuid NOT NULL, "componentType" "public"."employee_salary_components_componenttype_enum" NOT NULL, "calculationType" "public"."employee_salary_components_calculationtype_enum" NOT NULL DEFAULT 'fixed', "value" numeric(15,2) NOT NULL DEFAULT '0', "calculatedAmount" numeric(15,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_50352e5350238d0b1d82b2a2129" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ad83e5b6218790bc57da3cbfe6" ON "employee_salary_components" ("employeeSalaryStructureId", "salaryComponentId") `);
        await queryRunner.query(`CREATE TYPE "public"."salary_components_componenttype_enum" AS ENUM('earning', 'deduction')`);
        await queryRunner.query(`CREATE TYPE "public"."salary_components_calculationtype_enum" AS ENUM('fixed', 'percentage', 'formula', 'manual')`);
        await queryRunner.query(`CREATE TABLE "salary_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying(200) NOT NULL, "code" character varying(50) NOT NULL, "componentType" "public"."salary_components_componenttype_enum" NOT NULL, "calculationType" "public"."salary_components_calculationtype_enum" NOT NULL DEFAULT 'fixed', "defaultValue" numeric(15,2), "isTaxable" boolean NOT NULL DEFAULT false, "isRequired" boolean NOT NULL DEFAULT false, "accountId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_07f83a0db55d0f294bfff38fb74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2108be572385f86a99e850eade" ON "salary_components" ("businessId", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_440726da1cd2e97a13515aea59" ON "salary_components" ("businessId", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."pay_policy_components_calculationtype_enum" AS ENUM('fixed', 'percentage', 'formula', 'manual')`);
        await queryRunner.query(`CREATE TABLE "pay_policy_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "payPolicyId" uuid NOT NULL, "salaryComponentId" uuid NOT NULL, "calculationType" "public"."pay_policy_components_calculationtype_enum" NOT NULL DEFAULT 'manual', "value" numeric(15,2), "basedOnComponentId" uuid, "formula" text, "sortOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_8a72c06dd5afa7317106d345ce1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a03d7fc0a5b7f5d6b17c4acfe5" ON "pay_policy_components" ("payPolicyId", "salaryComponentId") `);
        await queryRunner.query(`CREATE TYPE "public"."pay_policies_payrolltype_enum" AS ENUM('monthly', 'weekly', 'daily', 'hourly')`);
        await queryRunner.query(`CREATE TYPE "public"."pay_policies_paycycle_enum" AS ENUM('monthly', 'weekly', 'bi_weekly', 'daily')`);
        await queryRunner.query(`CREATE TYPE "public"."pay_policies_salarycalculationtype_enum" AS ENUM('fixed', 'hourly', 'daily')`);
        await queryRunner.query(`CREATE TYPE "public"."pay_policies_workingdaystype_enum" AS ENUM('calendar_days', 'fixed_days', 'attendance_based')`);
        await queryRunner.query(`CREATE TYPE "public"."pay_policies_overtimeratetype_enum" AS ENUM('fixed', 'multiplier')`);
        await queryRunner.query(`CREATE TABLE "pay_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying(200) NOT NULL, "code" character varying(50) NOT NULL, "description" text, "payrollType" "public"."pay_policies_payrolltype_enum" NOT NULL DEFAULT 'monthly', "payCycle" "public"."pay_policies_paycycle_enum" NOT NULL DEFAULT 'monthly', "salaryCalculationType" "public"."pay_policies_salarycalculationtype_enum" NOT NULL DEFAULT 'fixed', "workingDaysType" "public"."pay_policies_workingdaystype_enum" NOT NULL DEFAULT 'fixed_days', "fixedWorkingDays" integer, "workingHoursPerDay" numeric(6,2), "currency" character varying(10) NOT NULL DEFAULT 'PKR', "overtimeAllowed" boolean NOT NULL DEFAULT false, "overtimeRateType" "public"."pay_policies_overtimeratetype_enum", "overtimeRate" numeric(10,4), "lateDeductionAllowed" boolean NOT NULL DEFAULT false, "absentDeductionAllowed" boolean NOT NULL DEFAULT true, "halfDayDeductionAllowed" boolean NOT NULL DEFAULT true, "taxApplicable" boolean NOT NULL DEFAULT false, "providentFundApplicable" boolean NOT NULL DEFAULT false, "eobiApplicable" boolean NOT NULL DEFAULT false, "socialSecurityApplicable" boolean NOT NULL DEFAULT false, "expenseAccountId" uuid, "payableAccountId" uuid, "isDefault" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_375bbc7d89f4ecfbb2366391a05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5dd4811fea165028c0bad706a8" ON "pay_policies" ("businessId", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d5d38a7f2484af5d3459ced0c9" ON "pay_policies" ("businessId", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."employees_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."employees_maritalstatus_enum" AS ENUM('single', 'married', 'divorced', 'widowed')`);
        await queryRunner.query(`CREATE TYPE "public"."employees_employmenttype_enum" AS ENUM('permanent', 'contract', 'intern', 'part_time', 'daily_wage')`);
        await queryRunner.query(`CREATE TYPE "public"."employees_employeestatus_enum" AS ENUM('active', 'inactive', 'resigned', 'terminated', 'on_leave')`);
        await queryRunner.query(`CREATE TYPE "public"."employees_salarypaymentmethod_enum" AS ENUM('cash', 'bank', 'cheque', 'online')`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "branchId" uuid, "departmentId" uuid NOT NULL, "designationId" uuid NOT NULL, "employeeCode" character varying(50) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100), "fullName" character varying(200) NOT NULL, "fatherName" character varying(150), "cnic" character varying(20), "email" character varying(150), "phone" character varying(30), "emergencyContact" character varying(200), "address" text, "gender" "public"."employees_gender_enum", "dateOfBirth" date, "maritalStatus" "public"."employees_maritalstatus_enum", "profileImage" character varying, "joiningDate" date NOT NULL, "leavingDate" date, "employmentType" "public"."employees_employmenttype_enum" NOT NULL DEFAULT 'permanent', "employeeStatus" "public"."employees_employeestatus_enum" NOT NULL DEFAULT 'active', "reportingManagerId" uuid, "shiftId" uuid, "attendancePolicyId" uuid, "leavePolicyId" uuid, "payPolicyId" uuid, "salaryPaymentMethod" "public"."employees_salarypaymentmethod_enum", "bankName" character varying(150), "bankAccountTitle" character varying(150), "bankAccountNumber" character varying(50), "iban" character varying(50), "taxNumber" character varying(50), "salaryAccountId" uuid, "createdBy" uuid, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_employees_business_email" ON "employees" ("businessId", "email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_employees_business_cnic" ON "employees" ("businessId", "cnic") WHERE "cnic" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_10f032b24d8320586a02ee92bd" ON "employees" ("businessId", "employeeCode") `);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying(200) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bc7b7f5061c02c08ee3ebe1c55" ON "departments" ("businessId", "name") `);
        await queryRunner.query(`ALTER TABLE "designations" ADD CONSTRAINT "FK_0cfc070511e279ae73e328bdea0" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ADD CONSTRAINT "FK_07733ed9558b0738b3d09240c8e" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ADD CONSTRAINT "FK_08395d6df652c5bf66fd9d7da8b" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ADD CONSTRAINT "FK_0a13b43a00450b1599378e05963" FOREIGN KEY ("payPolicyId") REFERENCES "pay_policies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" ADD CONSTRAINT "FK_7f26cec861380a830f1ad274f87" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" ADD CONSTRAINT "FK_30419832ce4a02944ce30b91c9d" FOREIGN KEY ("employeeSalaryStructureId") REFERENCES "employee_salary_structures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" ADD CONSTRAINT "FK_e91eaf712eabd8ccbe6b20211f1" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" ADD CONSTRAINT "FK_5dfe8d337c4296789b70ebc8da3" FOREIGN KEY ("salaryComponentId") REFERENCES "salary_components"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_components" ADD CONSTRAINT "FK_b05f4b6b07433bd09d06e95f422" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_components" ADD CONSTRAINT "FK_9f2266cad3438ffeac237cf7dee" FOREIGN KEY ("accountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" ADD CONSTRAINT "FK_5834b51c82940b9630a7c4c950f" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" ADD CONSTRAINT "FK_7b192d60aa12f8de114a4f70826" FOREIGN KEY ("payPolicyId") REFERENCES "pay_policies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" ADD CONSTRAINT "FK_14aba407d9fc2942a523dc270bf" FOREIGN KEY ("salaryComponentId") REFERENCES "salary_components"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" ADD CONSTRAINT "FK_1a9320798e8899c529d5b79d958" FOREIGN KEY ("basedOnComponentId") REFERENCES "salary_components"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_policies" ADD CONSTRAINT "FK_1380aeaf6d8c8448d948169a71b" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_policies" ADD CONSTRAINT "FK_6333c6bb211d4b72b0b0e9c2689" FOREIGN KEY ("expenseAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_policies" ADD CONSTRAINT "FK_cfb87d088bffc7245d07371657c" FOREIGN KEY ("payableAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_c0a85906f3a73c2b47f7699bda8" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_4edfe103ebf2fcb98dbb582554b" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_8eed4bfc75840eeb9780f017e9e" FOREIGN KEY ("designationId") REFERENCES "designations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_12c6c1ac43cccd5c7b71fe5e53a" FOREIGN KEY ("reportingManagerId") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_05d12964a104869fdb70ddb9cd9" FOREIGN KEY ("payPolicyId") REFERENCES "pay_policies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_52899653733ede49f2968d293f3" FOREIGN KEY ("salaryAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_88d327d7e13673e77bc0f741d3a" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_7c12fe0f6637fab88ef7f1791a9" FOREIGN KEY ("updatedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_561bf50b141a28df95c40885fb5" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_561bf50b141a28df95c40885fb5"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_7c12fe0f6637fab88ef7f1791a9"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_88d327d7e13673e77bc0f741d3a"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_52899653733ede49f2968d293f3"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_05d12964a104869fdb70ddb9cd9"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_12c6c1ac43cccd5c7b71fe5e53a"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_8eed4bfc75840eeb9780f017e9e"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_4edfe103ebf2fcb98dbb582554b"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_c0a85906f3a73c2b47f7699bda8"`);
        await queryRunner.query(`ALTER TABLE "pay_policies" DROP CONSTRAINT "FK_cfb87d088bffc7245d07371657c"`);
        await queryRunner.query(`ALTER TABLE "pay_policies" DROP CONSTRAINT "FK_6333c6bb211d4b72b0b0e9c2689"`);
        await queryRunner.query(`ALTER TABLE "pay_policies" DROP CONSTRAINT "FK_1380aeaf6d8c8448d948169a71b"`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" DROP CONSTRAINT "FK_1a9320798e8899c529d5b79d958"`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" DROP CONSTRAINT "FK_14aba407d9fc2942a523dc270bf"`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" DROP CONSTRAINT "FK_7b192d60aa12f8de114a4f70826"`);
        await queryRunner.query(`ALTER TABLE "pay_policy_components" DROP CONSTRAINT "FK_5834b51c82940b9630a7c4c950f"`);
        await queryRunner.query(`ALTER TABLE "salary_components" DROP CONSTRAINT "FK_9f2266cad3438ffeac237cf7dee"`);
        await queryRunner.query(`ALTER TABLE "salary_components" DROP CONSTRAINT "FK_b05f4b6b07433bd09d06e95f422"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" DROP CONSTRAINT "FK_5dfe8d337c4296789b70ebc8da3"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" DROP CONSTRAINT "FK_e91eaf712eabd8ccbe6b20211f1"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" DROP CONSTRAINT "FK_30419832ce4a02944ce30b91c9d"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_components" DROP CONSTRAINT "FK_7f26cec861380a830f1ad274f87"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" DROP CONSTRAINT "FK_0a13b43a00450b1599378e05963"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" DROP CONSTRAINT "FK_08395d6df652c5bf66fd9d7da8b"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" DROP CONSTRAINT "FK_07733ed9558b0738b3d09240c8e"`);
        await queryRunner.query(`ALTER TABLE "designations" DROP CONSTRAINT "FK_0cfc070511e279ae73e328bdea0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc7b7f5061c02c08ee3ebe1c55"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10f032b24d8320586a02ee92bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_business_cnic"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_business_email"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TYPE "public"."employees_salarypaymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employees_employeestatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employees_employmenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employees_maritalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employees_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5d38a7f2484af5d3459ced0c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5dd4811fea165028c0bad706a8"`);
        await queryRunner.query(`DROP TABLE "pay_policies"`);
        await queryRunner.query(`DROP TYPE "public"."pay_policies_overtimeratetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pay_policies_workingdaystype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pay_policies_salarycalculationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pay_policies_paycycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pay_policies_payrolltype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a03d7fc0a5b7f5d6b17c4acfe5"`);
        await queryRunner.query(`DROP TABLE "pay_policy_components"`);
        await queryRunner.query(`DROP TYPE "public"."pay_policy_components_calculationtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_440726da1cd2e97a13515aea59"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2108be572385f86a99e850eade"`);
        await queryRunner.query(`DROP TABLE "salary_components"`);
        await queryRunner.query(`DROP TYPE "public"."salary_components_calculationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."salary_components_componenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad83e5b6218790bc57da3cbfe6"`);
        await queryRunner.query(`DROP TABLE "employee_salary_components"`);
        await queryRunner.query(`DROP TYPE "public"."employee_salary_components_calculationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employee_salary_components_componenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c82a1f5127cd6c2578364a73dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_367fb367071532086460f2d9a9"`);
        await queryRunner.query(`DROP TABLE "employee_salary_structures"`);
        await queryRunner.query(`DROP TYPE "public"."employee_salary_structures_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de99aff7b406a20ad6329a5a82"`);
        await queryRunner.query(`DROP TABLE "designations"`);
    }

}
